using System;
class Program
{
    static void Main()
    {
        int divisor = 0;
        try
        {
            //nested try block
            try
            {
                int divideByZero = 6 / divisor;
                Console.WriteLine("Quotient :" + divideByZero);
            }
            //inner catch block
            catch (IndexOutOfRangeException e)
            {
                Console.WriteLine("Inner catch is executed." + e.Message);
            }
        }
        //outer catch block
        catch (DivideByZeroException e)
        {
            Console.WriteLine("Outer catch block is executed." + e.Message);
        }
    }
}
