using System;
class Program
{
    static void Main()
    {
        //int divisor = 0;
        try
        {
            //nested try block
            try
            {
                int[] divisor = { 1, 2, 3, 4, 5 };
                int divideByZero = 6 / divisor[6];
                Console.WriteLine("Quotient :" +divideByZero);
            }
            //inner catch block
            catch (IndexOutOfRangeException e)
            {
                Console.WriteLine("Inner catch is executed." + e.Message);
            }
        }
        //outer catch block
        catch (DivideByZeroException e)
        {
            Console.WriteLine("Outer catch block is executed." + e.Message);
        }
    }
}
